### ISSUE TITLE
Misunderstood mission

### ISSUE THREAD

**Issue by Totoajax** [JinweiClarkChao/one-two-three...infinity#16]
I can see many people misunderstood the mission. Instead of calculation, we just printed 1 to a billion. The ones I can see is:
- [C#](../blob/master/sum.cs)
- [Lisp](../blob/master/sum.lisp), I can't read that shit
- [Mathematica](../blob/master/sum.m)
- [Python](../blob/master/sum.py)
- [R](../blob/master/sum.r), maybe that one works, someone with knowledge should take a look at it
- [Scala](../blob/master/sum.scala), same as R
- [Shell](../blob/master/sum.sh), extra things

**Comment by JinweiClarkChao** [comment]
First of all, thanks for your interests in this toy project, @Totoajax .

I can understand your concern, for your information, although I cannot understand every language in the project, I tried my best to verify every language online. http://www.tutorialspoint.com/codingground.htm

As far as I know, C#, Lisp, Mathematica, Python, R and Scala **did** print the **result**, not print 1 to a billion. As for Shell, I removed extra displays. 

If you have any other ideas, you are always welcome to open issues and pull request. :smile:
